### ISSUE TITLE
PlayerState property on some PlayerPawns is null, or pointing to local PlayerState ???

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#175]
@kurozael was seeing enemies with his own name, which only happens if the PlayerState on another player is his own.

**Comment by Metapyziks** [comment]
Maybe related to this error on the host?

```
The type 'Facepunch.PlayerState' is not a supported dictionary key using converter of type 'Sandbox.JsonSerializedConvert`1[Facepunch.PlayerState]'. The unsupported member type is located on type 'System.Collections.Generic.List`1[Facepunch.DamageInfo]'. Path: $.	System.NotSupportedException: The type 'Facepunch.PlayerState' is not a supported dictionary key using converter of type 'Sandbox.JsonSerializedConvert`1[Facepunch.PlayerState]'. The unsupported member type is located on type 'System.Collections.Generic.List`1[Facepunch.DamageInfo]'. Path: $.
 ---> System.NotSupportedException: The type 'Facepunch.PlayerState' is not a supported dictionary key using converter of type 'Sandbox.JsonSerializedConvert`1[Facepunch.PlayerState]'.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyNameCore(Utf8JsonWriter writer, T value, JsonSerializerOptions options, Boolean isWritingExtensionDataProperty)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteNodeAsObject(Object value, JsonTypeInfo jsonTypeInfo)
   at Sandbox.Json.ToNode(Object obj, Type type)
   at Sandbox.Component.Serialize(SerializeOptions options)
```

**Comment by DevulTj** [comment]
This seems to happen a lot still.

**Comment by Metapyziks** [comment]
Possibly fixed, we'll see in the next test.

**Comment by Metapyziks** [comment]
![sbox_XzNTQVOfeR](https://github.com/user-attachments/assets/bac833a2-bb79-434c-894c-1a1342ec9f1d)

```
All players:
  PlayerState (skit4a):
    Id: b311f9e8-69a7-4164-a25c-ac16bdebfa1d
    DisplayName: skit4a
    IsConnected: True
    IsLocalPlayer: False
    Connection: 1eb54afb-c789-4841-907a-41371f3c49e7 (skit4a)
    Team: Terrorist
    UniqueId: 0
    TeamUniqueId: 0
    PlayerPawn: null
  PlayerState (Rosya):
    Id: 767dbd2e-052b-438c-b47a-6e8cd19f0ea6
    DisplayName: Rosya
    IsConnected: True
    IsLocalPlayer: False
    Connection: ec5fd019-39d0-4b85-a228-c8784a631d3d (Rosya)
    Team: Terrorist
    UniqueId: 3
    TeamUniqueId: 1
    PlayerPawn: 979fbe9f-8313-438b-b2e7-e39d4189c199
  PlayerState (qarman):
    Id: 338a7390-bcb5-45e4-8e0a-7aa043d66b8b
    DisplayName: qarman
    IsConnected: True
    IsLocalPlayer: False
    Connection: 7e768c3f-5299-4241-a5dc-4b6fe78caf35 (qarman)
    Team: Terrorist
    UniqueId: 13
    TeamUniqueId: 5
    PlayerPawn: 1e6226ba-8da3-4c4d-9557-9cd5508d7457
  PlayerState (BigBiba):
    Id: 6e44c7d1-4b46-4ef9-9d4b-68bface6bf7b
    DisplayName: BigBiba
    IsConnected: True
    IsLocalPlayer: False
    Connection: 382f99ea-9d67-43bf-9969-05fdc7af551d (BigBiba)
    Team: CounterTerrorist
    UniqueId: 1
    TeamUniqueId: 0
    PlayerPawn: null
  PlayerState (Snake):
    Id: 9e0963d7-b9a6-4372-8dec-1927a4470362
    DisplayName: Snake
    IsConnected: True
    IsLocalPlayer: False
    Connection: bcc4c6fe-9719-4c7e-be13-62a201f9b4b7 (Snake)
    Team: CounterTerrorist
    UniqueId: 9
    TeamUniqueId: 5
    PlayerPawn: null
  PlayerState (Jermios):
    Id: cb683120-f76c-4adc-9478-3d1028521f6c
    DisplayName: Jermios
    IsConnected: True
    IsLocalPlayer: False
    Connection: 3af0acc8-4fb4-4160-ab6c-f25ce7c5fcef (Jermios)
    Team: CounterTerrorist
    UniqueId: 2
    TeamUniqueId: 1
    PlayerPawn: null
  PlayerState (greiser):
    Id: b2a23206-2f7b-4313-8032-e83f09bdec77
    DisplayName: greiser
    IsConnected: True
    IsLocalPlayer: False
    Connection: b621892b-fb87-48f0-824c-68901d0277eb (greiser)
    Team: CounterTerrorist
    UniqueId: 14
    TeamUniqueId: 8
    PlayerPawn: null
  PlayerState (Globama):
    Id: 02533c3f-c682-4ca9-8d53-115e53dab583
    DisplayName: Globama
    IsConnected: True
    IsLocalPlayer: False
    Connection: cc96df89-3ffa-4366-9c2a-3000fc71de6c (Globama)
    Team: CounterTerrorist
    UniqueId: 16
    TeamUniqueId: 9
    PlayerPawn: null
  PlayerState (sticky nickest):
    Id: 086b8b34-46b6-4739-be0b-2b5a3407b85b
    DisplayName: sticky nickest
    IsConnected: True
    IsLocalPlayer: False
    Connection: 6319d5b4-56ff-461f-9c7b-d568459f6821 (sticky nickest)
    Team: CounterTerrorist
    UniqueId: 10
    TeamUniqueId: 6
    PlayerPawn: null
  PlayerState (Yukihira Soma):
    Id: dbe592fc-98ed-4b04-b427-8984a08526d4
    DisplayName: Yukihira Soma
    IsConnected: True
    IsLocalPlayer: False
    Connection: bea8671d-d87e-4ecb-a46f-1f02eda65e2f (Yukihira Soma)
    Team: Terrorist
    UniqueId: 5
    TeamUniqueId: 2
    PlayerPawn: 560a8907-11ad-49ec-9df6-87651295667c
  PlayerState (Cranch):
    Id: 84145832-a538-4da8-b697-2236faf1e4af
    DisplayName: Cranch
    IsConnected: True
    IsLocalPlayer: False
    Connection: 5f81d980-ff13-4028-9ca9-42317ad68e28 (Cranch)
    Team: Terrorist
    UniqueId: 17
    TeamUniqueId: 7
    PlayerPawn: null
  PlayerState (xczml):
    Id: b4581226-26ab-4ae1-a2db-cb7224bebbfc
    DisplayName: xczml
    IsConnected: True
    IsLocalPlayer: False
    Connection: d724f3ec-8dfe-4551-b83f-091ee2325d19 (xczml)
    Team: Terrorist
    UniqueId: 11
    TeamUniqueId: 4
    PlayerPawn: 83e55a73-4731-47e7-81a6-3b5fbb4fef7f
  PlayerState (Skuldent):
    Id: a6b59526-4c33-4630-9637-e357f2b275f2
    DisplayName: Skuldent
    IsConnected: True
    IsLocalPlayer: False
    Connection: 441b9ea1-a052-421f-a331-110bd119b3ac (Skuldent)
    Team: CounterTerrorist
    UniqueId: 12
    TeamUniqueId: 7
    PlayerPawn: null
  PlayerState (Krickmadam):
    Id: f386bfe1-34c1-40f9-9a96-c59ddc1586a2
    DisplayName: Krickmadam
    IsConnected: True
    IsLocalPlayer: False
    Connection: c4812a36-aec1-4651-a592-2f66d992d94a (Krickmadam)
    Team: Terrorist
    UniqueId: 15
    TeamUniqueId: 6
    PlayerPawn: null
  PlayerState (ziks):
    Id: eb9ad2dc-047d-4b56-af36-e87b95644e46
    DisplayName: ziks
    IsConnected: True
    IsLocalPlayer: True
    Connection: c3e9fcbf-faf2-45fc-aa7a-633a7921ea9e (ziks)
    Team: CounterTerrorist
    UniqueId: 18
    TeamUniqueId: 10
    PlayerPawn: 582f91fc-dfa5-47e8-b0b5-abbb24d68980

All pawns:
  Player (qarman):
    Id: 1e6226ba-8da3-4c4d-9557-9cd5508d7457
    DisplayName: ziks
    PlayerState: eb9ad2dc-047d-4b56-af36-e87b95644e46
  Player (Snake):
    Id: 1cc9af01-cf96-4660-918a-ee47d2230115
    DisplayName: Snake
    PlayerState: 9e0963d7-b9a6-4372-8dec-1927a4470362
  Player (greiser):
    Id: e90b8dc8-5b01-4a9e-9aea-851060debb24
    DisplayName: greiser
    PlayerState: b2a23206-2f7b-4313-8032-e83f09bdec77
  Player (BigBiba):
    Id: 17d4e94f-d483-44d0-8d66-13952c8514f8
    DisplayName: BigBiba
    PlayerState: 6e44c7d1-4b46-4ef9-9d4b-68bface6bf7b
  Player (xczml):
    Id: 83e55a73-4731-47e7-81a6-3b5fbb4fef7f
    DisplayName: ziks
    PlayerState: eb9ad2dc-047d-4b56-af36-e87b95644e46
  Player (sticky nickest):
    Id: 973a9646-0dc5-4d76-a2a4-075c1c9e11e6
    DisplayName: sticky nickest
    PlayerState: 086b8b34-46b6-4739-be0b-2b5a3407b85b
  Player (Cranch):
    Id: e70da287-a16a-48cd-a927-79f0a8c28590
    DisplayName: Cranch
    PlayerState: 84145832-a538-4da8-b697-2236faf1e4af
  Player (Globama):
    Id: 0db0cd8a-6676-45b8-98a8-6c42ea41fb1f
    DisplayName: Globama
    PlayerState: 02533c3f-c682-4ca9-8d53-115e53dab583
  Player (Skuldent):
    Id: 80033d55-e3ef-41fc-9dee-071253bab421
    DisplayName: Skuldent
    PlayerState: a6b59526-4c33-4630-9637-e357f2b275f2
  Player (skit4a):
    Id: 114ab1b3-4a71-4aae-bfff-617faf1b38fc
    DisplayName: skit4a
    PlayerState: b311f9e8-69a7-4164-a25c-ac16bdebfa1d
  Player (Krickmadam):
    Id: dfdb26ce-5b21-49b6-831f-42296c59f617
    DisplayName: Krickmadam
    PlayerState: f386bfe1-34c1-40f9-9a96-c59ddc1586a2
  Player (Jermios):
    Id: af8ddaf1-b7b4-47ea-9d6a-b10ef0d0e98c
    DisplayName: Jermios
    PlayerState: cb683120-f76c-4adc-9478-3d1028521f6c
  player:
    Id: 560a8907-11ad-49ec-9df6-87651295667c
    DisplayName: Yukihira Soma
    PlayerState: dbe592fc-98ed-4b04-b427-8984a08526d4
  player:
    Id: 582f91fc-dfa5-47e8-b0b5-abbb24d68980
    DisplayName: ziks
    PlayerState: eb9ad2dc-047d-4b56-af36-e87b95644e46
  player:
    Id: 979fbe9f-8313-438b-b2e7-e39d4189c199
    DisplayName: Rosya
    PlayerState: 767dbd2e-052b-438c-b47a-6e8cd19f0ea6

All connections:
  skit4a:
    Id: 1eb54afb-c789-4841-907a-41371f3c49e7
    DisplayName: skit4a
    PartyId: 0
    SteamId: 76561198068080400
    IsConnecting: False
    IsActive: True
  BigBiba:
    Id: 382f99ea-9d67-43bf-9969-05fdc7af551d
    DisplayName: BigBiba
    PartyId: 0
    SteamId: 76561199634770567
    IsConnecting: False
    IsActive: True
  Jermios:
    Id: 3af0acc8-4fb4-4160-ab6c-f25ce7c5fcef
    DisplayName: Jermios
    PartyId: 0
    SteamId: 76561199034191768
    IsConnecting: False
    IsActive: True
  Rosya:
    Id: ec5fd019-39d0-4b85-a228-c8784a631d3d
    DisplayName: Rosya
    PartyId: 0
    SteamId: 76561198300026203
    IsConnecting: False
    IsActive: True
  sticky nickest:
    Id: 6319d5b4-56ff-461f-9c7b-d568459f6821
    DisplayName: sticky nickest
    PartyId: 0
    SteamId: 76561198306010023
    IsConnecting: False
    IsActive: True
  Yukihira Soma:
    Id: bea8671d-d87e-4ecb-a46f-1f02eda65e2f
    DisplayName: Yukihira Soma
    PartyId: 0
    SteamId: 76561198312216269
    IsConnecting: False
    IsActive: True
  Cranch:
    Id: 5f81d980-ff13-4028-9ca9-42317ad68e28
    DisplayName: Cranch
    PartyId: 0
    SteamId: 76561198030411983
    IsConnecting: False
    IsActive: True
  Krickmadam:
    Id: c4812a36-aec1-4651-a592-2f66d992d94a
    DisplayName: Krickmadam
    PartyId: 0
    SteamId: 76561198090407127
    IsConnecting: False
    IsActive: True
  Snake:
    Id: bcc4c6fe-9719-4c7e-be13-62a201f9b4b7
    DisplayName: Snake
    PartyId: 0
    SteamId: 76561197995994474
    IsConnecting: False
    IsActive: True
  xczml:
    Id: d724f3ec-8dfe-4551-b83f-091ee2325d19
    DisplayName: xczml
    PartyId: 0
    SteamId: 76561198874894661
    IsConnecting: False
    IsActive: True
  Skuldent:
    Id: 441b9ea1-a052-421f-a331-110bd119b3ac
    DisplayName: Skuldent
    PartyId: 0
    SteamId: 76561198415052273
    IsConnecting: False
    IsActive: True
  qarman:
    Id: 7e768c3f-5299-4241-a5dc-4b6fe78caf35
    DisplayName: qarman
    PartyId: 0
    SteamId: 76561198369534916
    IsConnecting: False
    IsActive: True
  greiser:
    Id: b621892b-fb87-48f0-824c-68901d0277eb
    DisplayName: greiser
    PartyId: 0
    SteamId: 76561198998874849
    IsConnecting: False
    IsActive: True
  Антикрипер:
    Id: 9344ecde-f6b2-4e27-9b10-dfb777492d8a
    DisplayName: Антикрипер
    PartyId: 0
    SteamId: 76561199490101576
    IsConnecting: False
    IsActive: True
  Globama:
    Id: cc96df89-3ffa-4366-9c2a-3000fc71de6c
    DisplayName: Globama
    PartyId: 0
    SteamId: 76561198396888227
    IsConnecting: False
    IsActive: True
  local:
    Id: c3e9fcbf-faf2-45fc-aa7a-633a7921ea9e
    DisplayName: ziks
    PartyId: 0
    SteamId: 76561197992289728
    IsConnecting: False
    IsActive: True
```
